// Code generated by db2go. DO NOT EDIT.
package dataobject

var TableNameClasses = "classes" //

type ClassesDO struct {
	Id        int32  `json:"id,omitempty" db:"id" `                                 //incr id
	ClassNo   string `json:"class_no,omitempty" db:"class_no" `                     //class no
	UserId    int32  `json:"user_id,omitempty" db:"user_id" `                       //student id
	CreatedAt string `json:"created_at,omitempty" db:"created_at" sqlca:"readonly"` //create time
	UpdatedAt string `json:"updated_at,omitempty" db:"updated_at" sqlca:"readonly"` //update time
}

func (do *ClassesDO) GetId() int32          { return do.Id }
func (do *ClassesDO) SetId(v int32)         { do.Id = v }
func (do *ClassesDO) GetClassNo() string    { return do.ClassNo }
func (do *ClassesDO) SetClassNo(v string)   { do.ClassNo = v }
func (do *ClassesDO) GetUserId() int32      { return do.UserId }
func (do *ClassesDO) SetUserId(v int32)     { do.UserId = v }
func (do *ClassesDO) GetCreatedAt() string  { return do.CreatedAt }
func (do *ClassesDO) SetCreatedAt(v string) { do.CreatedAt = v }
func (do *ClassesDO) GetUpdatedAt() string  { return do.UpdatedAt }
func (do *ClassesDO) SetUpdatedAt(v string) { do.UpdatedAt = v }
