// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: classes_do.proto

package dataobject

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ClassesDO struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClassNo              string   `protobuf:"bytes,2,opt,name=class_no,json=classNo,proto3" json:"class_no,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassesDO) Reset()         { *m = ClassesDO{} }
func (m *ClassesDO) String() string { return proto.CompactTextString(m) }
func (*ClassesDO) ProtoMessage()    {}
func (*ClassesDO) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2d01f57cea8ae6f, []int{0}
}
func (m *ClassesDO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassesDO.Unmarshal(m, b)
}
func (m *ClassesDO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassesDO.Marshal(b, m, deterministic)
}
func (m *ClassesDO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassesDO.Merge(m, src)
}
func (m *ClassesDO) XXX_Size() int {
	return xxx_messageInfo_ClassesDO.Size(m)
}
func (m *ClassesDO) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassesDO.DiscardUnknown(m)
}

var xxx_messageInfo_ClassesDO proto.InternalMessageInfo

func (m *ClassesDO) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ClassesDO) GetClassNo() string {
	if m != nil {
		return m.ClassNo
	}
	return ""
}

func (m *ClassesDO) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ClassesDO) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ClassesDO) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*ClassesDO)(nil), "dataobject.ClassesDO")
}

func init() { proto.RegisterFile("classes_do.proto", fileDescriptor_b2d01f57cea8ae6f) }

var fileDescriptor_b2d01f57cea8ae6f = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0x49, 0x2c,
	0x2e, 0x4e, 0x2d, 0x8e, 0x4f, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x49,
	0x2c, 0x49, 0xcc, 0x4f, 0xca, 0x4a, 0x4d, 0x2e, 0x51, 0xea, 0x65, 0xe4, 0xe2, 0x74, 0x86, 0x28,
	0x70, 0xf1, 0x17, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62,
	0xca, 0x4c, 0x11, 0x92, 0xe4, 0xe2, 0x00, 0xeb, 0x8e, 0xcf, 0xcb, 0x97, 0x60, 0x52, 0x60, 0xd4,
	0xe0, 0x0c, 0x62, 0x07, 0xf3, 0xfd, 0xf2, 0x85, 0xc4, 0xb9, 0xd8, 0x4b, 0x8b, 0x53, 0x8b, 0xe2,
	0x33, 0x53, 0x24, 0x98, 0xc1, 0xea, 0xd9, 0x40, 0x5c, 0xcf, 0x14, 0x21, 0x59, 0x2e, 0xae, 0xe4,
	0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x94, 0xf8, 0xc4, 0x12, 0x09, 0x16, 0xb0, 0x2e, 0x4e, 0xa8, 0x88,
	0x63, 0x09, 0x48, 0xba, 0xb4, 0x20, 0x05, 0x26, 0xcd, 0x0a, 0x91, 0x86, 0x8a, 0x38, 0x96, 0x24,
	0xb1, 0x81, 0x9d, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x44, 0x9e, 0xfc, 0x99, 0xb6, 0x00,
	0x00, 0x00,
}
