// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users_do.proto

package dataobject

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UsersDO struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Disable              int32    `protobuf:"varint,6,opt,name=disable,proto3" json:"disable,omitempty"`
	Balance              float64  `protobuf:"fixed64,7,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersDO) Reset()         { *m = UsersDO{} }
func (m *UsersDO) String() string { return proto.CompactTextString(m) }
func (*UsersDO) ProtoMessage()    {}
func (*UsersDO) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2377d319209e61, []int{0}
}
func (m *UsersDO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersDO.Unmarshal(m, b)
}
func (m *UsersDO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersDO.Marshal(b, m, deterministic)
}
func (m *UsersDO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersDO.Merge(m, src)
}
func (m *UsersDO) XXX_Size() int {
	return xxx_messageInfo_UsersDO.Size(m)
}
func (m *UsersDO) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersDO.DiscardUnknown(m)
}

var xxx_messageInfo_UsersDO proto.InternalMessageInfo

func (m *UsersDO) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UsersDO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersDO) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UsersDO) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UsersDO) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UsersDO) GetDisable() int32 {
	if m != nil {
		return m.Disable
	}
	return 0
}

func (m *UsersDO) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *UsersDO) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UsersDO) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*UsersDO)(nil), "dataobject.UsersDO")
}

func init() { proto.RegisterFile("users_do.proto", fileDescriptor_cc2377d319209e61) }

var fileDescriptor_cc2377d319209e61 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xc1, 0x6a, 0x85, 0x30,
	0x10, 0x45, 0x89, 0xef, 0xa9, 0x75, 0x16, 0x52, 0x86, 0x2e, 0x66, 0x53, 0x90, 0xae, 0x5c, 0x75,
	0xd3, 0x2f, 0x10, 0xba, 0x2f, 0x08, 0x5d, 0xcb, 0xc4, 0x0c, 0x34, 0x45, 0x8d, 0x98, 0x08, 0xfd,
	0xd9, 0xfe, 0xcb, 0x23, 0x51, 0x77, 0xf7, 0xdc, 0x73, 0x13, 0x18, 0xa8, 0x77, 0x2f, 0x9b, 0x1f,
	0x8c, 0x7b, 0x5f, 0x37, 0x17, 0x1c, 0x82, 0xe1, 0xc0, 0x4e, 0xff, 0xca, 0x18, 0xde, 0xfe, 0x15,
	0x94, 0xdf, 0x51, 0x7f, 0x7e, 0x61, 0x0d, 0x99, 0x35, 0xa4, 0x1a, 0xd5, 0xe6, 0x7d, 0x66, 0x0d,
	0x22, 0xdc, 0x17, 0x9e, 0x85, 0xb2, 0x46, 0xb5, 0x55, 0x9f, 0x32, 0xbe, 0x40, 0xbe, 0xfe, 0xb8,
	0x45, 0xe8, 0x96, 0xca, 0x03, 0xf0, 0x19, 0x6e, 0x5e, 0xfe, 0xe8, 0x9e, 0x9e, 0xc6, 0x18, 0x77,
	0x32, 0xb3, 0x9d, 0x28, 0x3f, 0x76, 0x09, 0x90, 0xa0, 0x34, 0xd6, 0xb3, 0x9e, 0x84, 0x8a, 0xb4,
	0xbd, 0x30, 0x1a, 0xcd, 0x13, 0x2f, 0xa3, 0x50, 0xd9, 0xa8, 0x56, 0xf5, 0x17, 0xe2, 0x2b, 0xc0,
	0xb8, 0x09, 0x07, 0x31, 0x03, 0x07, 0x7a, 0x4a, 0xdf, 0x55, 0x67, 0xd3, 0x85, 0xa8, 0xf7, 0xd5,
	0x5c, 0xba, 0x3a, 0xf4, 0xd9, 0x74, 0x41, 0x17, 0xe9, 0xe4, 0x8f, 0x47, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x85, 0xa1, 0x23, 0xfa, 0x04, 0x01, 0x00, 0x00,
}
