// Code generated by db2go. DO NOT EDIT.
// https://github.com/civet148/sqlca

package models

const TableNameClasses = "classes" //

const (
	CLASSES_COLUMN_ID         = "id"
	CLASSES_COLUMN_CLASS_NO   = "class_no"
	CLASSES_COLUMN_USER_ID    = "user_id"
	CLASSES_COLUMN_CREATED_AT = "created_at"
	CLASSES_COLUMN_UPDATED_AT = "updated_at"
)

type ClassesDO struct {
	Id        int32  `json:"id" db:"id" bson:"id"`                                          //incr id
	ClassNo   string `json:"class_no" db:"class_no" bson:"class_no"`                        //class no
	UserId    int32  `json:"user_id" db:"user_id" bson:"user_id"`                           //student id
	CreatedAt string `json:"created_at" db:"created_at" sqlca:"readonly" bson:"created_at"` //create time
	UpdatedAt string `json:"updated_at" db:"updated_at" sqlca:"readonly" bson:"updated_at"` //update time
}

func (do *ClassesDO) GetId() int32          { return do.Id }
func (do *ClassesDO) SetId(v int32)         { do.Id = v }
func (do *ClassesDO) GetClassNo() string    { return do.ClassNo }
func (do *ClassesDO) SetClassNo(v string)   { do.ClassNo = v }
func (do *ClassesDO) GetUserId() int32      { return do.UserId }
func (do *ClassesDO) SetUserId(v int32)     { do.UserId = v }
func (do *ClassesDO) GetCreatedAt() string  { return do.CreatedAt }
func (do *ClassesDO) SetCreatedAt(v string) { do.CreatedAt = v }
func (do *ClassesDO) GetUpdatedAt() string  { return do.UpdatedAt }
func (do *ClassesDO) SetUpdatedAt(v string) { do.UpdatedAt = v }

/*
CREATE TABLE `classes` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'incr id',
  `class_no` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'class no',
  `user_id` int NOT NULL COMMENT 'student id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
*/
