// Code generated by db2go. DO NOT EDIT.
// https://github.com/civet148/sqlca

package models

const TableNameJsons = "jsons" //

const (
	JSONS_COLUMN_ID         = "id"
	JSONS_COLUMN_NAME       = "name"
	JSONS_COLUMN_SEX        = "sex"
	JSONS_COLUMN_USER_DATA  = "user_data"
	JSONS_COLUMN_CREATED_AT = "created_at"
	JSONS_COLUMN_UPDATED_AT = "updated_at"
)

type JsonsDO struct {
	Id        int32     `json:"id" db:"id" bson:"_id"`                                         //自增ID
	Name      string    `json:"name" db:"name" bson:"name"`                                    //用户名
	Sex       int32     `json:"sex" db:"sex" bson:"sex"`                                       //性别
	UserData  *UserData `json:"user_data" db:"user_data" bson:"user_data"`                     //用户JSON数据
	CreatedAt string    `json:"created_at" db:"created_at" sqlca:"readonly" bson:"created_at"` //创建时间
	UpdatedAt string    `json:"updated_at" db:"updated_at" sqlca:"readonly" bson:"updated_at"` //更新时间
}

func (do *JsonsDO) GetId() int32            { return do.Id }
func (do *JsonsDO) SetId(v int32)           { do.Id = v }
func (do *JsonsDO) GetName() string         { return do.Name }
func (do *JsonsDO) SetName(v string)        { do.Name = v }
func (do *JsonsDO) GetSex() int32           { return do.Sex }
func (do *JsonsDO) SetSex(v int32)          { do.Sex = v }
func (do *JsonsDO) GetUserData() *UserData  { return do.UserData }
func (do *JsonsDO) SetUserData(v *UserData) { do.UserData = v }
func (do *JsonsDO) GetCreatedAt() string    { return do.CreatedAt }
func (do *JsonsDO) SetCreatedAt(v string)   { do.CreatedAt = v }
func (do *JsonsDO) GetUpdatedAt() string    { return do.UpdatedAt }
func (do *JsonsDO) SetUpdatedAt(v string)   { do.UpdatedAt = v }

/*
CREATE TABLE `jsons` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `name` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '用户名',
  `sex` int NOT NULL DEFAULT '1' COMMENT '性别',
  `user_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户JSON数据',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
*/
