// Code generated by db2go. DO NOT EDIT.
// https://github.com/civet148/sqlca

package models

const TableNameTPoint = "t_point" //

const (
	T_POINT_COLUMN_ADDRES_ID     = "addres_id"
	T_POINT_COLUMN_ADDRESS_POINT = "address_point"
	T_POINT_COLUMN_LNG           = "lng"
	T_POINT_COLUMN_LAT           = "lat"
	T_POINT_COLUMN_NAME          = "name"
	T_POINT_COLUMN_GEOHASH       = "geohash"
)

type TPointDO struct {
	AddresId     uint64  `json:"addres_id" db:"addres_id" bson:"addres_id"`             //
	AddressPoint string  `json:"address_point" db:"address_point" bson:"address_point"` //
	Lng          float64 `json:"lng" db:"lng" bson:"lng"`                               //
	Lat          float64 `json:"lat" db:"lat" bson:"lat"`                               //
	Name         string  `json:"name" db:"name" bson:"name"`                            //
	Geohash      string  `json:"geohash" db:"geohash" bson:"geohash"`                   //
}

func (do *TPointDO) GetAddresId() uint64      { return do.AddresId }
func (do *TPointDO) SetAddresId(v uint64)     { do.AddresId = v }
func (do *TPointDO) GetAddressPoint() string  { return do.AddressPoint }
func (do *TPointDO) SetAddressPoint(v string) { do.AddressPoint = v }
func (do *TPointDO) GetLng() float64          { return do.Lng }
func (do *TPointDO) SetLng(v float64)         { do.Lng = v }
func (do *TPointDO) GetLat() float64          { return do.Lat }
func (do *TPointDO) SetLat(v float64)         { do.Lat = v }
func (do *TPointDO) GetName() string          { return do.Name }
func (do *TPointDO) SetName(v string)         { do.Name = v }
func (do *TPointDO) GetGeohash() string       { return do.Geohash }
func (do *TPointDO) SetGeohash(v string)      { do.Geohash = v }

/*
CREATE TABLE `t_point` (
  `addres_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `address_point` point NOT NULL,
  `lng` double(11,7) DEFAULT NULL,
  `lat` double(11,7) DEFAULT NULL,
  `name` char(80) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `geohash` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`addres_id`),
  SPATIAL KEY `address_point` (`address_point`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
*/
